Closes #22 4.5 inline formsets
thinknetica-django-lab-03/denm76 pull request #45
Opened 2021-06-12 09:56 UTC by denm76

Closes #22

2021-06-12 22:19 UTC, mikhailborodin requested changes

2021-06-12 22:19 UTC, mikhailborodin commented on bulletinboard/main/models.py
> +    image = models.ImageField(upload_to='announcement', blank=True)
поле не должно быть пустым

2021-06-12 22:19 UTC, mikhailborodin commented on bulletinboard/main/views.py
> +        bookInlineFormSet = inlineformset_factory(Auto, Picture, fields=('image',))
определение формсета надо вынести за метод, желательно в модуль forms.py

2021-06-12 22:19 UTC, mikhailborodin commented on bulletinboard/main/views.py
> +        car = Auto()
создавать инстанс Auto() не надо, так как при обработке POST запроса мы данные получаем из request
например вот так:
```
self.object = self.get_object(request)
formset_instance = FormSet(self.request.POST, self.request.FILES, instance=self.object)
```

2021-06-12 22:19 UTC, mikhailborodin commented on bulletinboard/templates/main/ads_processing/add_advert.html
> +    <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
в action надо всегда указывать урл

2021-06-18 15:42 UTC, morgangt approved these changes

2021-06-19 06:47 UTC, merged